Log:
  Level: debug # Log level: none, error, warning, info, debug
Nodes:
  - PanelType: "GoV2Panel" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel, BunPanel
    ApiConfig:
      ApiHost: "http://43.133.142.23:8080"
      ApiKey: "123456"
      NodeID: 8
      NodeType: Vless # Node type: V2ray, Vmess, Vless, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 5 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      VlessFlow: "xtls-rprx-vision" # Only support vless
    ControllerConfig:
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableREALITY: true # Enable REALITY
      REALITYConfigs:
        Show: true # Show REALITY debug
        Dest: www.microsoft.com:443 # Required, Same as fallback
        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
          - www.microsoft.com
        PrivateKey: QKLDX2zaVU896NbKhxzjtfKMusVOpIgbI2Iov_wWKEs # Required, execute './XrayR x25519' to generate
        ShortIds: # Required, list of available shortIds for the client, can be used to differentiate between different clients.
          - bd5c500d0928efd4